---
name: Dev
email: dev@mail.rit.edu
major: Computer Science
graduation: 2024
handle: dev
forges:
    GitHub: https://github.com/jrd4665
bio: Just a programmer with an urge to Unixize the world
public key: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----

    mQINBF88Y+ABEAC7qrPOqMQpWTERT68BZrcIyyN1k8+AZk6cU1vxIhCSzUN6AKOj
    qy0vv5zygq82DQLM6hybWJL8mXiPq0Or/Vh426z6bGj4K1KBxhbSlIcmYJm9oF8V
    T+j8wz2cVpF+hGzb6LmdL+25Dj7w7st9YaidY7MfHZi+j3/YCWwFe6ddKwBvvsjh
    xFSwPwx3p7OKqNcjq9NUBYC8ZRTxmzwwViJTeZsvLk9sNUK/huyhMfo3R8yjDhHZ
    2y3qo3TsDEK8hqv0GHZDIZ6H2nokGP1r93E8yviY43cnR2InuyVjiBJgCidr2sNt
    fe0wNE1SDYBKqoN/gaeUXNHiMNDvRR7pCQciwTpTaH0+nkfhRPBH/eGQqRr3Q3RC
    gIUsU8IsVg2gxDJEwO19Hun52JWrR/ZcW9ZudpHsyoxB1DCwBMjEuG4vcXzyce5s
    ufpoZ1XcSHUZ/Y2IJGyk3pMO6qO4rpD+6803hpy/9W+3iokFwlNFndhNqJ7Te1JU
    xv+uqU6szDorRxBCP/i7bQxEDNyvcqTw7x2K7/xdZNZkeNNDmWfb5dpIQWzEjpfM
    runtyyaiDcjssR4Ken3G2k3Fa+vc68/rmoBrwU0sraJIHy8wQu+oMAh3V2qpR4R2
    wq75BSJDbvEJ2QL7jlp+mbsTe8PVrsPMUZ2Zoky6Re2U+/88zU5FwBjBlQARAQAB
    tBpEZXYgUklUIDxkZXZAbWFpbC5yaXQuZWR1PokCTgQTAQgAOBYhBIx+nwQLtsI5
    m8+ZV7dfnxNHMFl4BQJfPGPgAhsDBQsJCAcCBhUKCQgLAgQWAgMBAh4BAheAAAoJ
    ELdfnxNHMFl4hLQP/2uhhZP6f2vPmPhbjIIUei9j6OkItZQAsqfAjqwNhsaz7sU8
    o0uuCrtOofKA2/hAPy9aCcZzL+4IWT3iBIrfNYrldGdv3JnaINDh6I1aG8puciKB
    cq+GUJAr44eH+LHipeyHPjX8VxsslIyhWBH3orMLg1IhKj1A9TWM8R/X3pmVP50c
    t2vHaMV3oJ3C1WiWmIs4YFc2wmJ2M8+mTfi29a5q0BNESjv3vCes2BcUiXqgYWY0
    PrhIptDjZ9y80BgyjlVLugvqQ3goX8ZL00Eij1es5anfBs1wxHygAPcVagWKPaRM
    k/bc8LN9HuXYdsgVGsXh2CALAXL3UYAayImTIm387s/nT4q8hQmNmwAp2ARs7NJ4
    JaaIvvxI5Ks9iFN7nJwnK/FnIBDEt4qy3N6pAQXb43+4pL8gIp6nEt1jGtfd3Ox3
    sZzVYM8XsTVuUbGBK3PnRElta2oUT0TgUmsHQWEGOWEur8Qmc1O2CIr0OW0P8+1N
    AoK+ttt0+PYxfj2TnHSgh3PhlMLMB+J2Cc5kwQpX+orSCP/FrQ+WiMsN8wZXgWHv
    R7Ivj90qRKj6zPkTAHnujeKoKmjE6A9eg/SyrpO75XT5GMBf5mS8cAmVsWp5JGIa
    RKcH3ALFS4hl43hNoClRvAkDrCt9PdvT+CjFJPL8qH/eULJWyYKPJ6+Ku27JuQIN
    BF88Y+ABEADdFDBucy22vnilp1tVOMxQQhbPxfLDxStHKpV7bYo5+MmBp3cT+WFQ
    TJa0cOTEVgNUy7vOWJdz5NAwWxDQJXnldUaGEhxibgTdMqtBJ/7oNxKwe2HNarle
    87tJGG30ZJs1PurfnRmXwFyz6koqHrDAhNLY9tQuzW2r80H5EfPNQebYqbfuVguG
    nQkBUiX02WOzSVxnsP1laqC0n6o1KEWT2kMyiKRw8kGxTfYqaUb2vEX/dcK9Vw80
    gwaudxVra+03xs2bRdKIosamOeFWcYmcNrDKblVmaR3MaLNX+qc4eO7jO15To5om
    Om+E4842HozM+4xijvXW8MLnSRQe9nXags5JvMkjwxN/a/1KgWkzPIA/VzrcdN7t
    qRqgPcqrSH0AfLWFcMdQk91IcsQoxiCrAK02Ir1r/PntYXAPJZmxvVqsaDdKCDEI
    2qgXMS2PabvB+qz8yiok6+tfoHIP2uiqcdQqsuu35CpXA8RLOo+5dS32Ji81csPV
    S8z6dgBHUroey0Zy5ONIuxqOXdG65VZK9wDcW4xwWBkTHEe2bSCACl7PX3bKUkM0
    mGoY+S23wyfcTJnFGuNw+yT1lo35P9Kgj+XPR61JCoBue2K9DF9TYDJYwMrBm5wF
    eQD9CO+ZQvF1MGcuL+r0gtok9NR2pMEv5vFG2IZFzeg0c/BVSFpfxQARAQABiQI2
    BBgBCAAgFiEEjH6fBAu2wjmbz5lXt1+fE0cwWXgFAl88Y+ACGwwACgkQt1+fE0cw
    WXg9NA//bp7p1hnqigCluUScsjWe2vudDp5EyNMZ6l5QdbwGCvBpUOPKKyEG5tCY
    EqoMDIn0Rp6VnBSrt6A7ppdgtY5GpAFSw9xKxESEM20VfcQSRPs2E5DaLutWACU1
    6qPn2BUSnskYErCh1zWS5ywMuoj3RU3Ba3m+a3wrreOpCDpT1IlHNMUR44maTXor
    ++PIhuFrERk4Ch8E4u/QSexrVIGpEgK6G6u2BMcwIWWUGruDFYOXkHN6VNxlWy3I
    cf3eel8tA6LPXg687+LzxbGDrrRWDfnugmVGmjjVDDAE9jzggEo7X9jPeZaToCE0
    X7F7cBF5d2Gj6oFMFW+lBi7oBIfD6tq15d2pWdINkWYNMc9mt9mZGPKQ9qaDjSkO
    Op5bwKujgfBMV3Nf4+Ba0VJwxrW2DQF16jtn3u8UfsygA43GTwnXj+xH6Efmwhg8
    JoXIBbNNserKWDvO0b3bUZbTYXddgjVxR6OktUc475SjvSLMZEUIatxOcL5P5b3e
    himRC9ea8I4IYjQwo/aa7nIlLhO8NQdw8W/qlJmt13i/c/ir+W+y0rNJ+nNj4wvC
    fT0QcCcyCxSiOIO/UKOinRrYGxhFh47JE6yr3bVGtRX1WlxKmSNXx1FbeDeUosL8
    AiH/puIn2lpu76QOa52Rvd1iZ/lV4/1XcjJ3dOXRR6RbXQ5FWRI=
    =4Yj7
    -----END PGP PUBLIC KEY BLOCK-----
